## The function makeCacheMatrix and the function cacheSolve defined in this page 
## are aimed to accelerate the calculating of a matrix's inverse. 
## The inverse is calculated once when the object generated by function makeCacheMatrix 
## is passed into the function cacheSolve for the first time. 
## After that, the returned values belong to the following calls on the same object are 
## got from the cache rather than calculated again and again. 
## By this way, the inverse calculating is accelerated.    
## The two functions should be used in pairs to prevent unexpected modification.   

## The function makeCacheMatrix generates matrices with a cache. 

makeCacheMatrix <- function(input)
{
    invX <- NULL
    x <- input
    set <- function(input)
    {
        x <<- input
        invX <<- NULL
    }
    get <- function()
    {
        x
    }
    setInvX <- function(input)
    {
        invX <<- input
    }
    getInvX <- function(input)
    {
        invX
    }
    list(set = set, get = get, setInvX = setInvX, getInvX = getInvX)
}


## The function cacheSolve will calculate the inverse of a matrix. 
## If this inverse has never been calculated, the value will be evaluated at once. 
## However, if we have assessed the inverse, 
## the value will be retrieved from the cache directly.

cacheSolve <- function(x, ...) 
{
        ## Return a matrix that is the inverse of 'x'
    if(is.null(x$getInvX()))
    {
        InvX <- solve(x$get())
        x$setInvX(InvX)
        return(InvX)
    }
    message("getting cached data")
    InvX <- x$getInvX()
    InvX
    
}
